### ISSUE TITLE
 Coins to hodl not working when mainMarket = EUR

### ISSUE THREAD

**Issue by IHateNameStealers** [TeamWertarbyte/crypto-trading-bot#10] opened 2021-01-10 13:50 UTC
The bot is selling / buying EUR - BTC's even when HODL is set to BTC. (ie: HODL:  ['BTC'], ['ETH']) and mainMarket = EUR.

**Comment by saschb2b** [comment] 2021-01-10 14:04
Seems you've set you hodl parameter wrong.
```
HODL: ['BTC', 'ETH'],
```
Would you mind pasting the mainMarket and hodl part fo your config here?
Will check other mainMarket compatibility within #9

**Comment by IHateNameStealers** [comment] 2021-01-10 17:19
Sure. I've removed bittrexApiKey and bittrexApiSecret

> const config: Config = {
  amountPerInvest: 20.0,
  bittrexApiKey: '..',
  bittrexApiSecret: '..',
  blacklist: ['DASH', 'GRIN', 'SOLVE', 'XMR', 'ZEC'],
  HODL: ['BTC', 'ETH'],
  refreshTimeout: 60000 * 60 * 0.05, // 3 min
  tickInterval: CandleInterval.DAY_1,
  mainMarket: 'EUR',
  minNegativeTicks: 2,
  exactPositiveTicks: 2
};
>

**Comment by saschb2b** [comment] 2021-01-10 18:31
@IHateNameStealers thanks for the configuration. 
Looks alright to me. I started work on #11 will test why other markets make problems

**Comment by saschb2b** [comment] 2021-01-17 16:46
Couldn't reproduce your issue. Maybe it was using an old configuration of yours?
With 2021.1.1 I added further logging regarding the configuration and how it is handled.
Maybe that will give you better insight on what could possible be wrong.

I close this issue for now. If you have further details feel free to reopen.

**Comment by saschb2b** [comment] 2021-01-28 07:47
So it sold my BTC which was a hodl coin. Main market USDT.
reopened. Will look into it again

**Comment by saschb2b** [comment] 2021-01-28 08:24
Ok I'm just stupid I guess. Hodl coins were protected against revenue sells but not against negativ ema evaluation rejections.
https://github.com/TeamWertarbyte/crypto-trading-bot/blob/master/src/modules/bot/index.ts#L217

**Closed** 2021-01-30 15:50 UTC
Labels: bug
